keys:
  # admin
  - &dorothy age1p3e9qvz8ykl0wz6rq2h5vxawyv2t93629c259qgstnmwdzrl95fshuplqk
  # cloud user
  - &cosimo age1xanc87qd0wk8srg479lz9pac8fwafhy3efm6csgx2kkm3h6jrgvsz4zxgs
  - &sheepro age1g5grzupkm8ch5t0gu6ydjqw4sagmq9vsqyqss66ejrtu98vgyggqv453wh
creation_rules:
  # e.g. hosts.d/cosimo/secrets.yaml
  - path_regex: hosts.d/cosimo/secrets(\.\w+)?\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *dorothy
      - *cosimo
  # e.g. hosts.d/cosimo/services/caddy.env
  - path_regex: hosts.d/cosimo/services/secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *dorothy
      - *cosimo
  # e.g. hosts.d/sheepro/secrets.yaml
  - path_regex: hosts.d/sheepro/secrets(\.\w+)?\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *dorothy
      - *sheepro
